# Generated by Django 2.2.5 on 2021-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210406_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Watches', 'WATCHES'), ('Sun Glasses', 'SUN GLASSES'), ('Shoes', 'SHOES'), ('Bags', 'BAGS')], default='Watches', max_length=155),
        ),
    ]
