# Generated by Django 2.2.5 on 2021-04-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210407_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Watches', 'WATCHES'), ('Sun Glasses', 'SUN GLASSES'), ('Shoes', 'SHOES'), ('Bags', 'BAGS')], default='Watches', max_length=155),
        ),
    ]
