# Generated by Django 2.2.5 on 2021-04-07 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Watches', 'WATCHES'), ('Sun Glasses', 'SUN GLASSES'), ('Shoes', 'SHOES'), ('Bags', 'BAGS')], default='Watches', max_length=155),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
