# Generated by Django 2.2.5 on 2021-04-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210407_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(default='500'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='1000'),
        ),
    ]
