# Generated by Django 2.2.5 on 2021-04-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210407_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_home',
        ),
    ]
