# Generated by Django 2.2.5 on 2021-04-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210407_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_home',
            name='category',
            field=models.CharField(choices=[('Watches', 'WATCHES'), ('Sun Glasses', 'SUN GLASSES'), ('Shoes', 'SHOES'), ('Bags', 'BAGS')], default='Watches', max_length=155),
        ),
    ]
